spring:
  application:
    name: web-front
  #    设置session超时时间为一天，86400秒
  session:
    timeout: 86400
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hzblf219
    url: jdbc:mysql://localhost:3306/dh_house?serverTimezone=UTC
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#    配置文件上传的解析器
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
#      必须指定以下的配置，springboot才能实现不通过后端来控制跳转
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/


dubbo:
  application:
    name: dubbodemo_consunmer # 给应用起名字
  protocol:
    name: dubbo
    port: -1


  #    配置注册中心
  registry:
    id: zk-registry
    address: zookeeper://localhost:2181
  consumer:
    check: false
server:
  port: 7004
#  配置路径的上下文
#  servlet:
#    context-path: /api


#mybatis-plus:
  #  global-config:
  #    db-config:
  #      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
  #      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
  #      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  configuration:
#    map-underscore-to-camel-case: true # 开启驼峰
#    log-dubbo.impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启日志
# 给实体类包起别名，这样就可以直接写实体名，因为是跨模块，所以要指定模块
# 因为添加了模块的依赖，所以就不需要指定包---直接写 type=model.AclAdmin
#  type-aliases-package: "model.src.main.java.model"

# todo: 后续学习一下分页插件pagehelper的使用
#pagehelper:
#  auto-dialect: on #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式
#  reasonable: true #分页合理化参数，默认值为 false 。当该参数设置为 true 时， pageNum<=0 时会查询第一页， pageNum>pages （超过总数时），会查询最后一页
#  support-methods-arguments: true #支持通过Mapper接口参数传递page参数,默认值为false
#  page-size-zero: true #默认值为 false ，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit =0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
#
